/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dm;

import javax.swing.*;

/**
 *
 * @author Ashish
 */
public class predict extends javax.swing.JFrame {
    JTable table;
    /**
     * Creates new form predict
     */
    public predict(){
        initComponents();
    }
    public predict(JTable table) {
        this.table=table;
        System.out.print(table.getModel().getRowCount());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class Label Prediction");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000-1200", "1200-1400", "1400-1600", "1600-2000", "2000-2400", "2400-2800" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agriculture", "Barren Rocky/Stony Waste", "Built up land", "Canal", "Crop Land in Forest", "Current Fallow", "Dense/Closed", "Forest Blanks", "Forest Plantations", "Industrial", "Lakes/Ponds", "Land with scrub", "Land without scrub", "Open (Evergreen/Semi evergreen)", "Open Deciduous (Moist/Dry)", "Plantations", "Rabi(Crop land)", "Recreational", "Reservoirs", "Residential", "River", "Scrub Forest", "Tanks", "Villages(Rural)" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0-1%", "1-3%", "3-5%", "5-8%", "8-15%", "15-30%", "30-60%", ">60%" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alkali Rocks", "Alkali,Peninsular,Migmatite,Khondalite,Champion", "Charnockite Group", "Peninsular Gneiss,Alkai,Satyamangalam,Charnockite", "Satyamangalam Group" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dome type Denudational Hills (Large)", "Dome type Residual Hills", "Habitation Mask", "Hilltop Weatered", "Intermontane valley/Structural Valley (Large)", "Ridge type Structural Hills (Large)", "Shallow Flood Plain", "Upper Piedmont Slope", "Valley Fill/filled in valley", "Water Body Mask" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0-0.000557", "0.000557-0.001113", "0.001113-0.00167", "0.00167-0.002226", "0.002226-0.002783" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLAYEY", "CLAYEY SKELETAL", "COARSE LOAMY", "FINE", "FINE LOAMY", "LOAMY", "LOAMY SKELETAL" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Predict");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jLabel2.setText("Land Use /Land Cover");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel3.setText("Rainfall");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel4.setText("Slope");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel5.setText("Rock Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel6.setText("Geomorphology");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel7.setText("Lineament");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel8.setText("Soil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("PREDICTION OF LANDSLIDE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-406)/2, (screenSize.height-610)/2, 406, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //jLabel1.setText(""+table.getModel().getRowCount());
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i,j,k,tempcc;
        String[] x=new String[7];
        String[] clabel;
        clabel = new String[5];
        int[] cclabel=new int[5];
        int rows,count_no[]=new int[7];
        double[] pclabel=new double[5];
        double[][] px_c=new double[5][7];
        double[] pX_C=new double[5];
        double[] pC_X=new double[5];
    
        for(i=0;i<5;i++){
            cclabel[i]=0;
        }
        clabel[0]="high";
        clabel[1]="very high";
        clabel[2]="low";
        clabel[3]="Moderate";
        clabel[4]="very low";
        x[0]=(String)jComboBox1.getSelectedItem();
        x[1]=(String)jComboBox2.getSelectedItem();
        x[2]=(String)jComboBox3.getSelectedItem();
        x[3]=(String)jComboBox4.getSelectedItem();
        x[4]=(String)jComboBox5.getSelectedItem();
        x[5]=(String)jComboBox6.getSelectedItem();
        x[6]=(String)jComboBox7.getSelectedItem();
        count_no[0]=jComboBox1.getItemCount();
        count_no[1]=jComboBox2.getItemCount();
        count_no[2]=jComboBox3.getItemCount();
        count_no[3]=jComboBox4.getItemCount();
        count_no[4]=jComboBox5.getItemCount();
        count_no[5]=jComboBox6.getItemCount();
        count_no[6]=jComboBox7.getItemCount();
        
        rows=table.getModel().getRowCount();
        
        
        //PROBABILITY OF CLASS LABELS
        
        
         for(j=0;j<5;j++){
                for(i=0;i<rows;i++){
            if(clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                cclabel[j]++;                
            }
            pclabel[j]=(double)(double)cclabel[j]/(double)rows;
            }
        }
          
         System.out.println("Probabitity of class labels:");
         for(i=0;i<5;i++){
             System.out.println(cclabel[i]+" "+pclabel[i]);
         }
         
         //PROBABILITY OF GIVEN CONDITION P(X|C)
         for(j=0;j<5;j++){
         for(i=0;i<rows;i++){                                 
                 if(x[0].compareTo((String)table.getModel().getValueAt(i,1))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][0]++;
                 }
                 if(x[1].compareTo((String)table.getModel().getValueAt(i,9))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][1]++;
                 }
                 if(x[2].compareTo((String)table.getModel().getValueAt(i,5))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][2]++;
                 }
                 if(x[3].compareTo((String)table.getModel().getValueAt(i,13))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][3]++;
                 }
                 if(x[4].compareTo((String)table.getModel().getValueAt(i,18))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][4]++;
                 }
                 if(x[5].compareTo((String)table.getModel().getValueAt(i,22))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][5]++;
                 }
                 if(x[6].compareTo((String)table.getModel().getValueAt(i,26))==0&&clabel[j].compareTo((String)table.getModel().getValueAt(i,31))==0){
                px_c[j][6]++;
                 }
            
             }
         //using laplasian corrector
         
         for(k=0;k<7;k++){
             tempcc=0;
             if(px_c[j][k]==0.0){
         px_c[j][k]=1;
         tempcc=cclabel[j]+count_no[k];
             }
             else{
                 tempcc=cclabel[j];
             }
         px_c[j][k]/=(double)tempcc;}
         
         }
       System.out.println("Probability of X_C for each attribute and label:");
         for(i=0;i<5;i++){
             for(j=0;j<7;j++){
                 System.out.print(" "+px_c[i][j]);
             }
             System.out.println();
         }
         
         
         for(j=0;j<5;j++){
               pX_C[j]=1.000000;
           }
       for(i=0;i<5;i++){
           for(j=0;j<7;j++){
               pX_C[i]=pX_C[i]*px_c[i][j];
           }
       }
       System.out.println("Probability of X_C for each class label");
       for(j=0;j<5;j++){
         System.out.println(pX_C[j]);
           }
       
         //USING NAIVE BAYSIAN TO PREDICT
         for(i=0;i<5;i++){
             pC_X[i]=pX_C[i]*pclabel[i];
         }
         System.out.println("Probability of C_X:");
         for(j=0;j<5;j++){
         System.out.println(pX_C[j]);
           }
         
        double max=0.0;
        for(i=0;i<5;i++){
            
                if(pC_X[i]>max){
                    max=pC_X[i];
                }
            }
        
        for(i=0;i<5;i++){            
                if(max==pC_X[i]){
                    break;
                }
                    }
       
        JOptionPane.showMessageDialog(null,"Landslide Prediction : "+clabel[i]);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(predict.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new predict().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
